config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'omniauth_callbacks/facebook'
    get 'omniauth_callbacks/vkontakte'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }

  resource :rooms
  resource :messages

  root "users#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  after_create_commit { ChatBroadcastJob.perform_later self }

  belongs_to :room
  belongs_to :user

  validates_presence_of :content, :room_id, :user_id



end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where("(rooms.sender_id = ? AND rooms.recipient_id =?) OR (rooms.sender_id = ? AND rooms.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/models/user.rb
class User < ApplicationRecord

  after_update_commit { AppearBroadcastJob.perform_later self }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :vkontakte]

  has_many :rooms, foreign_key: :sender_id
  has_many :messages


  def self.all_except(user)
    where.not(id: user)
  end


  def self.find_for_facebook_oauth access_token

    if user = User.where(uid: access_token.uid, provider: access_token.provider).first
      user
    else
      User.create!(:provider => access_token.provider,
                   :uid => access_token.uid,
                   :username => access_token.extra.raw_info.name,
                   :email => access_token.extra.raw_info.email,
                   :password => Devise.friendly_token[0,20])
    end

  end


  def self.find_for_vkontakte_oauth access_token

    if user = User.where(uid: access_token.uid, provider: access_token.provider).first
      user
    else
      User.create!(:provider => access_token.provider,
                   :uid => access_token.uid,
                   :username => access_token.info.name,
                   :email => access_token.uid+'@vk.com',
                   :password => Devise.friendly_token[0,20])
    end

  end


  def password_required?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save!

    redirect_to controller: 'rooms', action: 'show', id: @room.id

  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_user!

  def create
    if Room.between(params[:sender_id],params[:recipient_id]).present?
      @room = Room.between(params[:sender_id],params[:recipient_id]).first
    else
      @room = Room.create!(conversation_params)
    end

    redirect_to action: 'show', id: @room.id
  end

  def show
    @room = Room.find(params[:id])
    @reciever = reverse(@room)
    @messages = @room.messages
    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def reverse(room)
    current_user == room.recipient ? room.sender : room.recipient
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end


  def vkontakte
    @user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_action :configure_sign_in_params, only: [:create]

  def create
    if user = User.where(email: params[:user][:email]).first
      sign_in(:user, user)
      yield resource if block_given?
      redirect_to root_path
    else
      redirect_to new_user_registration_path
    end
  end

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attr])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all_except(current_user)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def check_username(object)
    object.username ? object.username : object.email
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_new.html.erb
<div class="new-message">
  <%= simple_form_for message, remote: true do |f| %>

      <%= f.input :content, as: :text, required: true, label: false, placeholder: 'Write your message hear...' %>
      <%= hidden_field_tag(:room_id, @room.id) %>

      <%= f.button :submit, 'send', class: 'btn btn-primary btn-message' %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<%= link_to '<< Back', root_path %>

<div class="header" current-user="<%= check_username(current_user) %>" recipient="<%= check_username(@reciever) %>">
  <h2 class="text-center">Chat</h2>
  <h4 class="text-center"><%= check_username(current_user) %> To: <%= check_username(@reciever) %> </h4>
</div>


<div class="chat" id=<%= @room.id %> user-id=<%= current_user.id %>>
  <div class="message-block">
    <% @messages.each do |message| %>
        <% if current_user.id ==  message.user_id %>
            <div class="current-user-message"><%= check_username(current_user) %></div>
            <div class="curr-msg-cont"><%= message.content %></div>
        <% else %>
            <div class="recipient-message"><%= check_username(@reciever) %></div>
            <div class="res-msg-cont"><%= message.content %></div>
        <% end %>
    <% end %>
  </div>
  <%= render 'messages/new', message: @message  %>
</div>

app/views/users/index.html.erb
<%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "logout_header" %>


<h4 class="text-center">Signed in as: <%= check_username(current_user) %></h4>

<h2>Other registered users:</h2>

<% @users.each do |user| %>
    <div class="user">
      <div class="user-status" data=<%= user.id %>>
        <% if user.appear == true %>
            <div class="status" style="background-color: deepskyblue;"></div>
        <% else %>
            <div class="status" style="background-color: white;"></div>
        <% end %>
      </div>
      <div class="user-email">
        <%= check_username(user) %>
      </div>
      <div class="user-button">
        <%= button_to "open chat", rooms_path, params: {sender_id: current_user.id, recipient_id: user.id}, class: 'btn btn-primary btn-chat' %>
      </div>
    </div>
<% end %>